name: Deploy Node.js app to Azure Web App - Onboarding-project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install dependencies in backend directory
        run: |
          cd backend
          npm install
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MYAPP }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Onboarding-project'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_a514ed6f7fe74293ad5defddb0bcede7 }}
          package: .
